version: "3"

tasks:
  # # Lind and test (local)

  lint: # https://github.com/super-linter/super-linter
    desc: "GitHub Super-Linter"
    cmds:
      - source .github/scripts/test.sh && gh_super_linter

  # # Scan with Checkov (local)

  checkov: # https://www.checkov.io/
    desc: "Checkov, find cloud infra misconfigurations"
    cmds:
      - source .github/scripts/test.sh && checkov

  # # Scan with Trivy (local)

  trivy: # https://github.com/aquasecurity/trivy
    desc: "Trivy security scanner"
    cmds:
      - source .github/scripts/test.sh && trivy
