version: "3"

env:
  CLUSTER_NAME: pattern
  KUBE: export KUBECONFIG=/mnt/c/Users/devops/.kube/config

includes:
  # Include the helper tasks
  helper_tasks: utils/helper_tasks.yml

tasks:
  create:
    desc: |
      Create cluster
      Set Kubeconfig env var manually ==> export KUBECONFIG=/mnt/c/Users/devops/.kube/config
    cmds:
      - '[ -z "$KUBECONFIG" ] && echo "Set KUBECONFIG env var ==> {{.KUBE}}" && exit 1 || k3d cluster create {{.CLUSTER_NAME}} --agents 2'
    status:
      - k3d cluster list | grep {{.CLUSTER_NAME}} # If cluster exists, skip the task
    silent: true

  deploy:
    desc: "Deploy the configs in text/"
    cmds:
      - task: create
      - kubectl apply -f kube/

  delete:
    desc: "Delete cluster"
    cmds:
      - k3d cluster delete {{.CLUSTER_NAME}}
    silent: true

  test:
    cmds:
      - echo '{{if eq OS "windows"}}{{OS}}{{else}}{{OS}}{{end}}'
